### ISSUE TITLE
Systems to add

### ISSUE THREAD

**Issue by Gaizure** [SaraVieira/lets-play-retro-games#6]
Here's the reminder you requested from twitter.

In addition to adding Game Gear and Master System, you also might consider adding Sega 32X and NEC TurboGrafx 16!

**Comment by TJ09** [comment]
DOS games would also be nice, especially ones that are already available on archive.org for easy access.

**Comment by SaraVieira** [comment]
Heeey

Making a list here 

- [x] Master System
- [x] Game Gear
- [x] 32X
- [x] NEC TurboGrafx 16
- [x]  Sega Saturn
- [x] Virtual Boy
- [x] PS1
- [ ] DOS

**Comment by SaraVieira** [comment]
@Gaizure Master system and game gear added! Will add the next two today and probably also the sega dreamcast or saturn

@TJ09 Will try to add DOS games but according to wikipedia there ar 4000 of them ;/

**Comment by Gaizure** [comment]
A nice little feature you might consider adding is for the user to be able to get a random game from all of the available categories or add checkboxes next to each one so they could get get a random game from several systems of their choosing.

**Comment by SaraVieira** [comment]
So you have normal random and then *advanced* random? 

Wish me luck in that SQL query ahaha

**Comment by SaraVieira** [comment]
All system but dos added

Also added Virtual boy because why not

new issue opened for super random

https://github.com/SaraVieira/lets-play-retro-games/issues/9

closing this
