### ISSUE TITLE
"Copy game url" button only copies part of the URL 

### ISSUE THREAD

**Issue by dromerstein** [SaraVieira/lets-play-retro-games#7]
MacOS 11.6.7, reproduced in both Safari 15.5 and Chrome 105.0.5195.52.

Action: go to any random game, click "Copy game url"
Expected result: a complete URL in the form of 'https://letsplayretro.games/SYSTEM_ID/GAME_ID' would be copied to the clipboard, ready to be pasted into a browser bar, etc.
Actual result: the bare 'GAME_ID' is copied to the clipboard

Example: https://letsplayretro.games/snes/random just now gave me the SNES game 'Thunder Spirits'. The copied game url is 'thunder-spirits', not the expected 'https://letsplayretro.games/snes/thunder-spirits'

**Comment by SaraVieira** [comment]
I know exactly what happened

I made this button before I got the domain and never remembered to go back and add the rest of the url 🤦

**Comment by SaraVieira** [comment]
Fixed and pused
