### ISSUE TITLE
Copy url button not clickable on mobile 

### ISSUE THREAD

**Issue by duarteocarmo** [SaraVieira/lets-play-retro-games#8]
Video: 
https://twitter.com/i/status/1568167177915621377

Bom ver-te a construir merdas! MORE SHITY WEBSITES PLEASSSSSEEE

**Comment by duarteocarmo** [comment]
Not that this one is shity. You know what I mean.

**Comment by SaraVieira** [comment]
Wow, calling my websites shiity

Wow ahahah

Fixed! :D
<img width="377" alt="CleanShot 2022-09-12 at 23 30 01@2x" src="https://user-images.githubusercontent.com/1051509/189752799-87640f11-33ca-482d-8d7e-45f9f56f65b4.png">
